#!/usr/bin/env python
"""Update airport codes from OurAirports public dataset.

Downloads the latest airports.csv and generates config/airport_codes.yaml.

Usage:
    python scripts/update_airport_codes.py

OurAirports data is public domain (CC0).
Source: https://ourairports.com/data/
"""

from __future__ import annotations

import csv
import logging
import sys
from pathlib import Path
from urllib.request import urlopen

import yaml

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

# OurAirports CSV URL (public domain)
AIRPORTS_URL = "https://davidmegginson.github.io/ourairports-data/airports.csv"

# Output path
CONFIG_PATH = Path("config/airport_codes.yaml")

# IATA codes to include (filter to major airports)
# Only include airports with scheduled passenger service (type = "large_airport" or "medium_airport")
# and that have an IATA code


def download_airports_csv() -> list[dict]:
    """Download and parse OurAirports CSV."""
    logger.info(f"Downloading {AIRPORTS_URL} ...")

    try:
        response = urlopen(AIRPORTS_URL, timeout=60)
        content = response.read().decode("utf-8")
    except Exception as e:
        logger.error(f"Failed to download: {e}")
        sys.exit(1)

    reader = csv.DictReader(content.splitlines())
    airports = list(reader)
    logger.info(f"Loaded {len(airports)} airports from OurAirports")
    return airports


def filter_to_major_airports(airports: list[dict]) -> dict[str, str]:
    """Filter to major airports with IATA codes.

    Returns dict mapping IATA code to "City Country" string.
    """
    result = {}

    for airport in airports:
        iata = airport.get("iata_code", "").strip()
        airport_type = airport.get("type", "")
        municipality = airport.get("municipality", "").strip()
        iso_region = airport.get("iso_region", "").strip()
        iso_country = airport.get("iso_country", "").strip()

        # Skip if no IATA code
        if not iata or len(iata) != 3:
            continue

        # Only include large and medium airports (scheduled service)
        if airport_type not in ("large_airport", "medium_airport"):
            continue

        # Build location string
        # Prefer municipality name, fall back to region name
        if municipality:
            # Convert "US-CA" style region to state/country
            if iso_region.startswith("US-"):
                state = iso_region[3:]
                location = f"{municipality} {state}"
            else:
                # Non-US: use municipality + country code
                location = f"{municipality} {iso_country}"
        elif iso_region:
            location = f"{iso_region} {iso_country}"
        else:
            location = iso_country

        result[iata] = location

    logger.info(f"Filtered to {len(result)} airports with IATA codes")
    return result


def merge_with_existing(new_codes: dict[str, str]) -> dict[str, str]:
    """Merge new codes with existing config, preserving manual additions."""
    if not CONFIG_PATH.exists():
        return new_codes

    with open(CONFIG_PATH) as f:
        existing = yaml.safe_load(f) or {}

    # Count existing entries
    existing_count = len(existing)
    merged = {**new_codes, **existing}  # existing overrides new (preserve manual edits)

    logger.info(f"Merged {len(new_codes)} new codes with {existing_count} existing entries")
    return merged


def write_config(codes: dict[str, str]) -> None:
    """Write airport codes to YAML config."""
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Sort by code
    sorted_codes = dict(sorted(codes.items()))

    # Add header comment
    header = """# Airport IATA codes mapped to city/region
#
# Format: CODE: "City State/Country"
#
# Generated by: python scripts/update_airport_codes.py
# Source: OurAirports (https://ourairports.com/data/) - public domain
#
# Manual edits are preserved. Add custom codes at the bottom.

"""

    with open(CONFIG_PATH, "w") as f:
        f.write(header)
        yaml.dump(sorted_codes, f, default_flow_style=False, sort_keys=False)

    logger.info(f"Wrote {len(sorted_codes)} airport codes to {CONFIG_PATH}")


def main():
    logger.info("Updating airport codes from OurAirports...\n")

    # Download
    airports = download_airports_csv()

    # Filter to major airports with IATA codes
    codes = filter_to_major_airports(airports)

    # Merge with existing (preserves manual additions)
    merged = merge_with_existing(codes)

    # Write config
    write_config(merged)

    logger.info("\nDone! Airport codes updated.")
    logger.info(f"To add custom codes, edit {CONFIG_PATH}")


if __name__ == "__main__":
    main()